apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side
  namespace: min-side
  labels:
    team: min-side
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  envFrom:
    - secret: tms-min-side-secrets
  image: {{image}}
  port: 3000
  liveness:
    path: /minside/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /minside/api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /minside/api/internal/metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: tms-min-side-proxy
        - application: tms-mikrofrontend-selector
        - application: tms-varsel-api
        - application: tms-utbetalingsoversikt-api
        - application: tms-utkast
        - application: mine-saker-api
        - application: pensjonskalkulator-microfrontend-ssr
          namespace: pensjonskalkulator
        - application: tiltakspenger-meldekort-microfrontend
          namespace: tpts
        - application: meldekort-mikrofrontend
          namespace: meldekort
        - application: aia-min-side-ssr
          namespace: paw
        - application: pam-min-side-microfrontend
          namespace: teampam
        - application: ungdomsprogramytelse-innsyn-mikrofrontend-ssr
          namespace: dusseldorf
        - application: k9-innsyn-dine-pleiepenger-mikrofrontend-ssr
          namespace: dusseldorf
        - application: familie-ba-minside-mikrofrontend
          namespace: teamfamilie
        - application: familie-ef-mikrofrontend-minside
          namespace: teamfamilie
        - application: ao-min-side-microfrontend-ssr
          namespace: dab
        - application: aap-min-side-microfrontend
          namespace: aap
        - application: mine-klager-microfrontend
          namespace: klage
        - application: aktivitetskrav-microfrontend
          namespace: team-esyfo
        - application: dialogmote-microfrontend
          namespace: team-esyfo
        - application: meroppfolging-microfrontend
          namespace: team-esyfo
  ingresses:
    - "https://www.intern.dev.nav.no/minside"
    - "https://www.ansatt.dev.nav.no/minside"
  env:
    - name: AKTUELT_URL
      value: "http://tms-mikrofrontend-selector/aktuelt"
    - name: UTKAST_URL
      value: "https://www.ansatt.dev.nav.no/minside/utkast"
    - name: UTKAST_API_URL
      value: "http://tms-utkast/v2/utkast/antall"
    - name: VARSLER_URL
      value: "https://www.ansatt.dev.nav.no/minside/varsler"
    - name: VARSEL_API_URL
      value: "http://tms-varsel-api/tms-varsel-api/ssr/antall/aktive"
    - name: DIN_OVERSIKT_URL
      value: "http://tms-mikrofrontend-selector/din-oversikt"
    - name: MELDEKORT_URL
      value: "http://meldekort-mikrofrontend.meldekort"
    - name: MIN_SIDE_URL
      value: "https://www.ansatt.dev.nav.no/minside"
    - name: DOKUMENTARKIV_URL
      value: "https://www.ansatt.dev.nav.no/dokumentarkiv"
    - name: DOKUMENTER_URL
      value: "http://mine-saker-api/mine-saker-api/ssr/journalposter/siste"
    - name: INNBOKS_URL
      value: "https://innboks.dev.nav.no"
    - name: NAVN_URL
      value: "http://tms-min-side-proxy/tms-min-side-proxy/personalia"
    - name: UTBETALINGSOVERSIKT_API_URL
      value: "http://tms-utbetalingsoversikt-api/tms-utbetalingsoversikt-api/utbetalinger/ssr/siste"
    - name: UTBETALINGSOVERSIKT_URL
      value: "https://www.ansatt.dev.nav.no/utbetalingsoversikt"
    - name: REDIRECT_URI
      value: "https://www.ansatt.dev.nav.no/minside"
    - name: PUBLIC_TELEMETRY_URL
      value: "https://telemetry.ekstern.dev.nav.no/collect"
    - name: PUBLIC_LEGACY_SELECTOR_URL
      value: "https://www.ansatt.dev.nav.no/tms-min-side-proxy/selector/din-oversikt"
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
